application:
  name: kurzio-web
  project: kurzio
  publicly_accessible: true
  port: 1000
routers:
- name: main
  custom_domains:
  - branch: master
    domain: kurzio.sk
  routes:
  - application_name: kurzio-web
    paths:
    - /